import type { IndianStateCode } from "./indian-states";

/**
 * States served by each 2-digit pincode prefix (India Post sorting zones). Deliberately
 * loose — some zones span several states — so it's only used to warn about likely typos,
 * never to block an order.
 */
const ZONES: Record<string, IndianStateCode[]> = {
  "11": ["DL"],
  "12": ["HR"],
  "13": ["HR", "PB"],
  "14": ["PB", "HR"],
  "15": ["PB"],
  "16": ["PB", "CH", "HR"],
  "17": ["HP"],
  "18": ["JK"],
  "19": ["JK", "LA"],
  "20": ["UP"],
  "21": ["UP"],
  "22": ["UP"],
  "23": ["UP"],
  "24": ["UP", "UT"],
  "25": ["UP"],
  "26": ["UP", "UT"],
  "27": ["UP"],
  "28": ["UP"],
  "30": ["RJ"],
  "31": ["RJ"],
  "32": ["RJ"],
  "33": ["RJ"],
  "34": ["RJ"],
  "36": ["GJ", "DH"],
  "37": ["GJ"],
  "38": ["GJ"],
  "39": ["GJ", "DH"],
  "40": ["MH", "GA"],
  "41": ["MH"],
  "42": ["MH"],
  "43": ["MH"],
  "44": ["MH"],
  "45": ["MP"],
  "46": ["MP"],
  "47": ["MP"],
  "48": ["MP"],
  "49": ["CT"],
  "50": ["TG", "AP"],
  "51": ["AP", "TG"],
  "52": ["AP"],
  "53": ["AP"],
  "56": ["KA"],
  "57": ["KA"],
  "58": ["KA"],
  "59": ["KA"],
  "60": ["TN", "PY"],
  "61": ["TN"],
  "62": ["TN"],
  "63": ["TN"],
  "64": ["TN"],
  "67": ["KL", "PY"],
  "68": ["KL", "LD"],
  "69": ["KL"],
  "70": ["WB"],
  "71": ["WB"],
  "72": ["WB"],
  "73": ["WB", "SK"],
  "74": ["WB", "AN"],
  "75": ["OR"],
  "76": ["OR"],
  "77": ["OR"],
  "78": ["AS", "ML", "AR"],
  "79": ["AR", "MN", "ML", "MZ", "NL", "TR", "AS"],
  "80": ["BR"],
  "81": ["BR", "JH"],
  "82": ["JH", "BR"],
  "83": ["JH"],
  "84": ["BR"],
  "85": ["BR", "JH"],
};

/** false only when the pincode clearly belongs to a different state. Unknown prefixes pass. */
export function pincodeMatchesState(pincode: string, stateCode: string): boolean {
  const states = ZONES[pincode.slice(0, 2)];
  return !states || (states as string[]).includes(stateCode);
}
